import { field, group } from '@nuxt/content/preview'

export default defineNuxtSchema({
  appConfig: {
    content: group({
      title: 'Content',
      description: 'Content collection and routing configuration.',
      icon: 'i-lucide-file-text',
      fields: {
        collections: group({
          title: 'Collections',
          description:
            'Content collections. Each can be a string (name) or object { name, type, prefix?, backLabel? }.',
          icon: 'i-lucide-database',
          fields: {
            docs: group({
              title: 'Docs',
              description: 'Documentation collection configuration (page type).',
              icon: 'i-lucide-book',
              fields: {
                name: field({
                  type: 'string',
                  title: 'Collection Name',
                  description: 'Name of the docs collection.',
                  default: 'docs',
                }),
                type: field({
                  type: 'string',
                  title: 'Collection Type',
                  description: 'Type of collection: "page" (routable) or "data" (not routable).',
                  default: 'page',
                  required: ['page', 'data'],
                }),
                prefix: field({
                  type: 'string',
                  title: 'URL Prefix',
                  description:
                    'URL prefix for docs (e.g., "/docs", "/darksky").',
                  default: '/docs',
                }),
              },
            }),
            pages: group({
              title: 'Pages',
              description: 'Pages collection configuration (page type).',
              icon: 'i-lucide-file',
              fields: {
                name: field({
                  type: 'string',
                  title: 'Collection Name',
                  description: 'Name of the pages collection.',
                  default: 'pages',
                }),
                type: field({
                  type: 'string',
                  title: 'Collection Type',
                  description: 'Type of collection: "page" (routable) or "data" (not routable).',
                  default: 'page',
                  required: ['page', 'data'],
                }),
                prefix: field({
                  type: 'string',
                  title: 'URL Prefix',
                  description: 'URL prefix for pages (e.g., "/" for root).',
                  default: '/',
                }),
                backLabel: field({
                  type: 'string',
                  title: 'Back Label',
                  description: 'Label for back navigation button.',
                  default: 'Back to Articles',
                }),
              },
            }),
            glossary: group({
              title: 'Glossary',
              description: 'Glossary collection configuration (data type).',
              icon: 'i-lucide-book-open',
              fields: {
                name: field({
                  type: 'string',
                  title: 'Collection Name',
                  description: 'Name of the glossary collection.',
                  default: 'glossary',
                }),
                type: field({
                  type: 'string',
                  title: 'Collection Type',
                  description: 'Type of collection: "page" (routable) or "data" (not routable).',
                  default: 'data',
                  required: ['page', 'data'],
                }),
              },
            }),
            references: group({
              title: 'References',
              description: 'References collection configuration (data type).',
              icon: 'i-lucide-quote',
              fields: {
                name: field({
                  type: 'string',
                  title: 'Collection Name',
                  description: 'Name of the references collection.',
                  default: 'references',
                }),
                type: field({
                  type: 'string',
                  title: 'Collection Type',
                  description: 'Type of collection: "page" (routable) or "data" (not routable).',
                  default: 'data',
                  required: ['page', 'data'],
                }),
              },
            }),
            faq: group({
              title: 'FAQ',
              description: 'FAQ collection configuration (data type).',
              icon: 'i-lucide-help-circle',
              fields: {
                name: field({
                  type: 'string',
                  title: 'Collection Name',
                  description: 'Name of the FAQ collection.',
                  default: 'faq',
                }),
                type: field({
                  type: 'string',
                  title: 'Collection Type',
                  description: 'Type of collection: "page" (routable) or "data" (not routable).',
                  default: 'data',
                  required: ['page', 'data'],
                }),
              },
            }),
            config: group({
              title: 'Config',
              description: 'Config collection configuration (data type).',
              icon: 'i-lucide-settings',
              fields: {
                name: field({
                  type: 'string',
                  title: 'Collection Name',
                  description: 'Name of the config collection.',
                  default: 'config',
                }),
                type: field({
                  type: 'string',
                  title: 'Collection Type',
                  description: 'Type of collection: "page" (routable) or "data" (not routable).',
                  default: 'data',
                  required: ['page', 'data'],
                }),
              },
            }),
            navigation: group({
              title: 'Navigation',
              description: 'Navigation collection configuration (data type).',
              icon: 'i-lucide-menu',
              fields: {
                name: field({
                  type: 'string',
                  title: 'Collection Name',
                  description: 'Name of the navigation collection.',
                  default: 'navigation',
                }),
                type: field({
                  type: 'string',
                  title: 'Collection Type',
                  description: 'Type of collection: "page" (routable) or "data" (not routable).',
                  default: 'data',
                  required: ['page', 'data'],
                }),
              },
            }),
            searchable: field({
              type: 'array',
              title: 'Searchable Collections',
              description: 'Collections to include in search results.',
              icon: 'i-lucide-search',
              default: ['docs'],
            }),
          },
        }),
        routing: group({
          title: 'Routing',
          description: 'Additional URL paths not tied to specific collections.',
          icon: 'i-lucide-route',
          fields: {
            sources: field({
              type: 'string',
              title: 'Sources Path',
              description: 'URL path for sources/references page.',
              icon: 'i-lucide-library',
              default: '/sources',
            }),
            offers: field({
              type: 'string',
              title: 'Offers Path',
              description: 'URL path for offers section.',
              icon: 'i-lucide-tag',
              default: '/offers',
            }),
            success: field({
              type: 'string',
              title: 'Success Path',
              description: 'URL path for success pages.',
              icon: 'i-lucide-check-circle',
              default: '/success',
            }),
          },
        }),
      },
    }),
    ui: group({
      title: 'UI',
      description: 'UI Customization.',
      icon: 'i-lucide-palette',
      fields: {
        colors: group({
          title: 'Colors',
          description: 'Manage main colors of your application',
          icon: 'i-lucide-palette',
          fields: {
            primary: field({
              type: 'string',
              title: 'Primary',
              description: 'Primary color of your UI.',
              icon: 'i-lucide-palette',
              default: 'green',
              required: [
                'red',
                'orange',
                'amber',
                'yellow',
                'lime',
                'green',
                'emerald',
                'teal',
                'cyan',
                'sky',
                'blue',
                'indigo',
                'violet',
                'purple',
                'fuchsia',
                'pink',
                'rose',
              ],
            }),
            neutral: field({
              type: 'string',
              title: 'Neutral',
              description: 'Neutral color of your UI.',
              icon: 'i-lucide-palette',
              default: 'slate',
              required: ['slate', 'gray', 'zinc', 'neutral', 'stone'],
            }),
          },
        }),
        icons: group({
          title: 'Icons',
          description: 'Manage icons used in the application.',
          icon: 'i-lucide-settings',
          fields: {
            search: field({
              type: 'icon',
              title: 'Search Bar',
              description: 'Icon to display in the search bar.',
              icon: 'i-lucide-search',
              default: 'i-lucide-search',
            }),
            dark: field({
              type: 'icon',
              title: 'Dark mode',
              description: 'Icon of color mode button for dark mode.',
              icon: 'i-lucide-moon',
              default: 'i-lucide-moon',
            }),
            light: field({
              type: 'icon',
              title: 'Light mode',
              description: 'Icon of color mode button for light mode.',
              icon: 'i-lucide-sun',
              default: 'i-lucide-sun',
            }),
            external: field({
              type: 'icon',
              title: 'External Link',
              description: 'Icon for external link.',
              icon: 'i-lucide-external-link',
              default: 'i-lucide-external-link',
            }),
            chevron: field({
              type: 'icon',
              title: 'Chevron',
              description: 'Icon for chevron.',
              icon: 'i-lucide-chevron-down',
              default: 'i-lucide-chevron-down',
            }),
            hash: field({
              type: 'icon',
              title: 'Hash',
              description: 'Icon for hash anchors.',
              icon: 'i-lucide-hash',
              default: 'i-lucide-hash',
            }),
          },
        }),
      },
    }),
    logo: group({
      title: 'Logo',
      description: 'Header logo configuration.',
      icon: 'i-lucide-image',
      fields: {
        light: field({
          type: 'media',
          title: 'Light Mode Logo',
          description: 'Pick an image from your gallery.',
          icon: 'i-lucide-sun',
          default: '',
        }),
        dark: field({
          type: 'media',
          title: 'Dark Mode Logo',
          description: 'Pick an image from your gallery.',
          icon: 'i-lucide-moon',
          default: '',
        }),
        alt: field({
          type: 'string',
          title: 'Alt',
          description: 'Alt to display for accessibility.',
          icon: 'i-lucide-text',
          default: '',
        }),
      },
    }),
    seo: group({
      title: 'SEO',
      description: 'SEO configuration.',
      icon: 'i-lucide-search',
      fields: {
        title: field({
          type: 'string',
          title: 'Title',
          description: 'Title to display in the header.',
          icon: 'i-lucide-type',
          default: '',
        }),
        description: field({
          type: 'string',
          title: 'Description',
          description: 'Description to display in the header.',
          icon: 'i-lucide-type',
          default: '',
        }),
      },
    }),
    header: group({
      title: 'Header',
      description: 'Header configuration.',
      icon: 'i-lucide-layout',
      fields: {
        title: field({
          type: 'string',
          title: 'Title',
          description: 'Title to display in the header.',
          icon: 'i-lucide-type',
          default: '',
        }),
      },
    }),
    socials: field({
      type: 'object',
      title: 'Social Networks',
      description: 'Social links configuration.',
      icon: 'i-lucide-network',
      default: {},
    }),
    toc: group({
      title: 'Table of contents',
      description: 'TOC configuration.',
      icon: 'i-lucide-list',
      fields: {
        title: field({
          type: 'string',
          title: 'Title',
          description: 'Title of the table of contents.',
          icon: 'i-lucide-heading',
          default: 'On this page',
        }),
        bottom: group({
          title: 'Bottom',
          description: 'Bottom section of the table of contents.',
          icon: 'i-lucide-list',
          fields: {
            title: field({
              type: 'string',
              title: 'Title',
              description: 'Title of the bottom section.',
              icon: 'i-lucide-heading',
              default: 'Community',
            }),
            links: field({
              type: 'array',
              title: 'Links',
              description: 'Links to display in the bottom section.',
              icon: 'i-lucide-link',
              default: [],
            }),
          },
        }),
      },
    }),
    github: group({
      title: 'GitHub',
      description: 'GitHub configuration.',
      icon: 'i-simple-icons-github',
      fields: {
        url: field({
          type: 'string',
          title: 'URL',
          description: 'GitHub URL.',
          icon: 'i-simple-icons-github',
          default: '',
        }),
        branch: field({
          type: 'string',
          title: 'Branch',
          description: 'GitHub branch.',
          icon: 'i-lucide-git-branch',
          default: 'main',
        }),
        rootDir: field({
          type: 'string',
          title: 'Root Directory',
          description: 'Root directory of the GitHub repository.',
          icon: 'i-lucide-folder',
          default: '',
        }),
      },
    }),
  },
})
