# pnpm-workspace.yaml
packages:
  # Core apps
  - 'apps/docs'

  # Only include specific examples we're building
  - 'examples/founder-funnel/web'
  - 'examples/founder-funnel/docs'
  - 'examples/astronera/web'
  - 'examples/astronera/docs'
  - 'examples/starter/web'
  - 'examples/starter/docs'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - unrs-resolver
  - vue-demi

onlyBuiltDependencies:
  - better-sqlite3
  - sharp
